### ISSUE TITLE
Genesys II startup failed

### ISSUE THREAD

**Issue by Wen-Sheng** [openhwgroup/cva6-platform#10]
Hi~ this is a very impressive project. 
I'd like to ask, when I try to use Genesys II: Getting Started, after turning on the Genesys II power, the UART stops responding and shows the following situation..
Is there anything I forgot to do?

[ TIME ] Timed out waiting for device dev-hvc0.device - /dev/hvc0.
[DEPEND] Dependency failed for seri…ervice - Serial Getty on hvc0.
[  OK  ] Finished systemd-udev-trig…e - Coldplug All udev Devices.
[  OK  ] Reached target sysinit.target - System Initialization.
[  OK  ] Started dnf-makecache.timer - dnf makecache --timer.
[  OK  ] Started fstrim.timer - Discard unused blocks once a week.
[  OK  ] Started systemd-tmpfiles-c… Cleanup of Temporary Directories.
[  OK  ] Started unbound-anchor.tim… the root trust anchor for DNSSEC.
[  OK  ] Reached target timers.target - Timer Units.
[  OK  ] Listening on dbus.socket▒▒- D-Bus System Message Bus Socket.
[  OK  ] Listening on pcscd.socket▒▒art Card Daemon Activation Socket.
[  OK  ] Reached target sockets.target - Socket Units.
[  OK  ] Reached target basic.target - Basic System.
         Starting dracut-shutdown.s…tore /run/initramfs on shutdown...
         Starting systemd-logind.se…ice - User Login Management...
         Starting systemd-user-sess…vice - Permit User Sessions...
[  OK  ] Finished dracut-shutdown.s…estore /run/initramfs on shutdown.
[FAILED] Failed to start systemd-lo…rvice - User Login Management.
See 'systemctl status systemd-logind.service' for details.
[  OK  ] Stopped systemd-logind.service - User Login Management.
         Starting modprobe@drm.service - Load Kernel Module drm...
[  OK  ] Finished systemd-user-sess…ervice - Permit User Sessions.
[  OK  ] Finished modprobe@drm.service - Load Kernel Module drm.
[  OK  ] Started getty@hvc0.service - Getty on hvc0.
[  OK  ] Started getty@tty1.service - Getty on tty1.
[  OK  ] Reached target getty.target - Login Prompts.
         Starting systemd-logind.se…ice - User Login Management...
[FAILED] Failed to start systemd-lo…rvice - User Login Management.
See 'systemctl status systemd-logind.service' for details.
[  OK  ] Stopped systemd-logind.service - User Login Management.
         Starting modprobe@drm.service - Load Kernel Module drm...

**Comment by Jbalkind** [comment]
Could you tell me a little more about your setup and what exactly you're running? If I remember right there would be some delay but generally hvc0 would come up eventually and then the boot would continue. It's also possible that your write to the SD could have had a minor corruption which could cause issues.

**Comment by Wen-Sheng** [comment]
Thank you for your response~ 
Here are my steps.
1. Download the bitstream and image files. (Based on your workflow.)
2. Use BalenaEtcher to flash the image onto the SD card.
3. Put the bitstream onto a USB flash drive.
4. Adjust JP4 to USB mode and JP5 to USB/SD mode. (The rest remains unchanged.)
5. Insert the UART. (The remaining connections are not used.)
6. Adjust the serial port to 115200 (I am using MobaXterm).
7. Power on the Genesys 2.
The terminal will freeze at the point mentioned above...

**Comment by Jbalkind** [comment]
Could you try making sure you have the right UART config? Specifically I believe we're using what's known as 115200 8n1. I think we had a user the other day who had hardware flow control enabled and it wasn't working.

**Comment by Wen-Sheng** [comment]
Thank you very much for your response~
It was my mistake, the serial port display is at the top, I overlooked it...

**Comment by Jbalkind** [comment]
Aha! Well I'm glad you have it working now :)
